### ISSUE TITLE
move /blog to blog.sysarmy.com

### ISSUE THREAD

**Issue by axelvf** [sysarmy/sysarmy.github.io#10]
Hace falta moverlo a blog.sysarmy.com? Pregunto porque todos los links apuntan a https://sysarmy.wordpress.com

**Comment by edux** [comment]
hay que ver con ajolo que onda porque en las birras hablamos de salir de wordpress y pasar a algo como pelican o algun engine estatico, se te ocurre alguno que podamos sumar aca facilmente?

**Comment by axelvf** [comment]
Si, sino jekyll que se que se usa bastante en github pages.

**Comment by edux** [comment]
el que sea me da igual, podes armar un /blog en master con un dummy post
como para probar y documentar un toque como agregar contenido? asi despues
migramos los blog posts.

**Comment by axelvf** [comment]
Dale, lo veo en la semana y les cuento

**Comment by axelvf** [comment]
@edux Aparentemente hay una tool de migración, necesito acceso al Wordpress, mi user es axvasquez2016

**Comment by axelvf** [comment]
Queda con un redirect al WP por el momento hasta definir nuevo CMS
