### ISSUE TITLE
Rules en Cloudflare

### ISSUE THREAD

**Issue by axelvf** [sysarmy/sysarmy.github.io#11]
@arieljolo Pongamos acá las reglas que hay que crear en CF

**Comment by ajolo2ky** [comment]
/help/?qa=feed/questions.rss =>
https://help.sysarmy.com/?qa=feed/questions.rss
/blog/feed/ => https://sysarmy.wordpress.com/feed/
/help/?qa=feed/qa.rss => https://help.sysarmy.com/?qa=feed/qa.rss
<https://help.sysarmy.com/?qa=feed/questions.rss>

**Comment by ajolo2ky** [comment]
Sigo esperando respuesta de CF :shrug

**Comment by ajolo2ky** [comment]
Aplicadas en CF
