### ISSUE TITLE
Fix links

### ISSUE THREAD

**Issue by axelvf** [sysarmy/sysarmy.github.io#15]
Estaba viendo y hay un par de links que habría que corregir, pongo la lista para que me confirmen:

IRC: http://webchat.freenode.net/?channels=#sysarmy --> https://webchat.freenode.net/?channels=#sysarmy

Slack: http://bit.ly/nerdslack --> https://bit.ly/nerdslack

Facebook: https://www.facebook.com/adminfest

Twitter: https://twitter.com/sysarmy

Instagram: https://instagram.com/sysarmy

Linkedin: http://www.linkedin.com/groups?gid=4736196 --> https://www.linkedin.com/groups?gid=4736196

Meetup: http://www.meetup.com/sysarmy/ --> https://www.meetup.com/sysarmy/

Mailinglist: http://listas.usla.org.ar/cgi-bin/mailman/listinfo/sysarmy --> https://listas.usla.org.ar/cgi-bin/mailman/listinfo/sysarmy

Adminbirras: (duplicado Meetup) https://meetup.com/sysarmy

La versión en inglés ademas cuenta con estos 2 links:
Help: http://sysarmy.com.ar/help --> https://help.sysarmy.com

Blog: http://www.sysarmy.com.ar/blog --> https://sysarmy.wordpress.com/

**Comment by edux** [comment]
Los únicos que veo que hay que corregir.

Facebook: https://www.facebook.com/nerdearla
Linkedin: https://www.linkedin.com/groups/4736196/

Y habría que poner los que faltan en español tambien así quedan igual.  Lo podes armar?

**Comment by axelvf** [comment]
@edux checkealo
