### ISSUE TITLE
Migración del blog

### ISSUE THREAD

**Issue by axelvf** [sysarmy/sysarmy.github.io#17]
Esta semana voy a ver si puedo comenzar con la migración del blog a Hugo.
@arieljolo tenes por algun lado el bkp del viejo WP? faltan las imágenes de los primeros posts.

**Comment by edux** [comment]
si esta en DO puedo mirar si lo encuentro me confirmas jolo?

**Comment by ajolo2ky** [comment]
Ahí relinkeé los archivos que no estaban, faltan solamente las fotos de
Ramón que sé que las tengo en algún lado. Esto no es un stopper para
empezar con la migración

**Comment by axelvf** [comment]
Perfecto Jolo! Gracias!
En el export mando una imagen dummy y después la reemplazamos

**Comment by axelvf** [comment]
Olvidate de las imágenes de Ramón que ya las conseguí

**Comment by axelvf** [comment]
Primera versión disponible: https://sysarmy.com/blog/

**Comment by edux** [comment]
:) <3

**Comment by axelvf** [comment]
Acepto sugerencias, cambios y/o puteadas

**Comment by edux** [comment]
hay algun readme de como probarlo localmente? o los md los tenes vos por
ahora?

**Comment by axelvf** [comment]
Los tengo por ahora hasta que veamos lo del submódulo.
Igual voy a armar un breve readme.MD con los pasos a realizar y luego hago
transfer del repo

**Comment by axelvf** [comment]
Creé el repo en mi cuenta pero no tengo permisos para transferirlo.

![image](https://user-images.githubusercontent.com/10050288/56987649-5ba5b980-6b64-11e9-9f2a-529445d7ae96.png)

**Comment by edux** [comment]
ahi te mande invite a la org, fijate si ahora podes

**Comment by axelvf** [comment]
Acepte y me tira el mismo error

**Comment by axelvf** [comment]
Migrado y transferido :)
