### ISSUE TITLE
Descripccion de los programas en Podcast se ven sin saltos de linea

### ISSUE THREAD

**Issue by jorge-1987** [sysarmy/sysarmy.github.io#20]
<img width="744" alt="Screen Shot 2019-08-06 at 16 49 43" src="https://user-images.githubusercontent.com/6954744/62572554-6611d680-b86a-11e9-92b1-5e7388a7ee86.png">

Mejorar la forma en la que se ven las descripcciones.

**Comment by edux** [comment]
https://podcasters.spotify.com/terms/Spotify_Podcast_Delivery_Specification_v1.5.pdf

**Comment by edux** [comment]
Me parece que no se puede fixear @jorge-1987 mira esto https://docs.google.com/spreadsheets/d/1x4PCyXANvKDebosNBi8lZpsgQ0pMhBVzwOK0ceNi0X8/edit#gid=0

**Comment by edux** [comment]
Lo cierro porque no veo que haya fix. podemos reabrir si aparece algo para probar.
