### ISSUE TITLE
Links de invitacion a slack expirados.

### ISSUE THREAD

**Issue by vmariano** [sysarmy/sysarmy.github.io#22]
![slack-bug](https://user-images.githubusercontent.com/796960/73039377-8a6f6880-3e34-11ea-8018-78c058bcb7a6.gif)

No encontre mucho relacionado a esto en el help center de slack, 

Lo que mas o menos parece tener sentido es este thread que Quora: https://www.quora.com/Is-there-a-way-to-enable-anyone-to-join-a-Slack  donde proponen un par de soluciones.

🤷‍♂

**Comment by edux** [comment]
Proba con este short link https://sysar.my/slack creo que el del website estaba dead.

**Comment by vmariano** [comment]
Perfecto, funcionó.

**Comment by ajolo2ky** [comment]
Fixeado el link que estaba apuntando al anterior en la versión en español de la web. Gracias por reportar.
