### ISSUE TITLE
Imagenes desactualizadas por workflow que fallo

### ISSUE THREAD

**Issue by Nachichuri** [sysarmy/sysarmy.github.io#26]
Rompio el workflow de [pages-build-deployments#53](https://github.com/sysarmy/sysarmy.github.io/actions/runs/3960193436).

Con los cambios en 93616ce tambien se cambiaron hrefs de imagenes en varios sites, pero al romper el build quedaron imagenes viejas.

Habria que triggerear el workflow de nuevo a mano o pushear a master asi se triggerea, no tengo permissions para hacerlo yo.

**Comment by axelvf** [comment]
Gracias @Nachichuri por el aviso. Lo reviso.

**Comment by axelvf** [comment]
Solucionado @Nachichuri.
Se pueden ver los logos actualizados en mirrors: https://mirrors.eze.sysarmy.com/
<img width="658" alt="image" src="https://user-images.githubusercontent.com/10050288/215274817-aac03d65-a252-40e7-bbf7-a09b7810feef.png">

cc @ajolo2ky
