### ISSUE TITLE
move /help to help.sysarmy.com

### ISSUE THREAD

**Issue by edux** [sysarmy/sysarmy.github.io#7]

**Comment by axelvf** [comment]
@edux pasame los datos del equipo para hacer los cambios

**Comment by edux** [comment]
@godlike64 vos tenes /help? o estaba perdido en otro lugar?

**Comment by axelvf** [comment]
GAAAAAAADLAAAAAAAAAIIIIKKKK

**Comment by godlike64** [comment]
Migrado a help.sysarmy.com. A mi me parece funcionar todo bien, prueben igual (no probé crear preguntas ni responder).

**Comment by axelvf** [comment]
Gracias @godlike64! 
Quedó creada la redirección. Ya se puede apuntar desde CF @edux?

**Comment by edux** [comment]
Supongo que si, jolo tiene que meter el cambio en CF nose si eso ya lo
hablaron por whatsapp

**Comment by axelvf** [comment]
Listo!
