### ISSUE TITLE
Alguna forma de tener el stock de remeras

### ISSUE THREAD

**Issue by edux** [sysarmy/sysarmy.github.io#8]
quizas tener /swag y ahi poner un link al spreadsheet de remeras o simplemente manejarlo en markdown.

esto es lo que esta ahora. https://goo.gl/krTFGD idealmente habría que agregar una galeria de los motivos.

**Comment by lemil** [comment]
Y que tal un e-commerce? Si lo quieren me avisan y lo levantamos en 5.

**Comment by edux** [comment]
Ya intentamos eso y es un overkill de mantenimiento para algo que es esporádico y eventual.

**Comment by zingaya** [comment]
Si te parece le digo a mi hermano que haga algo sencillo en php + mysql.

**Comment by edux** [comment]
es que php+mysql es overkill tambien, yo pensaba en algo static que parsee un json o algo de ese tipo y que yo pueda actualizar manualmente con un commit.

**Comment by edux** [comment]
Closing, this is moving to tienda nube.
